# Generated by Django 6.1.1 on 2026-09-08 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(db_index=True, help_text='e.g. TN 66 AY 1092', max_length=30, unique=True)),
                ('vehicle_type', models.CharField(default='Lorry', max_length=50)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('owner_name', models.CharField(default='Own Fleet', max_length=150)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
    ]
