# Generated by Django 5.2.17 on 2026-09-12 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Insurance', 'Insurance'), ('RC', 'RC / Registration Certificate'), ('FC', 'FC / Fitness Certificate'), ('Permit', 'Permit'), ('PUC', 'PUC / Pollution Certificate'), ('Road Tax', 'Road Tax'), ('National Permit', 'National Permit'), ('Driver Licence', 'Driver Licence'), ('Other', 'Other Vehicle Document')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='vehicle_documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-is_active', 'expiry_date'],
            },
        ),
    ]
