# Generated by Django 5.2.17 on 2026-09-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicledocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocumentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.IntegerField(help_text='Days left when reminder generated (e.g. 30, 15, 0)')),
                ('is_notified', models.BooleanField(default=False, help_text='True if shown to user on screen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vehicles.vehicledocument')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('document', 'reminder_type')},
            },
        ),
    ]
