# Generated by Django 6.1.1 on 2026-09-08 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DECIMAL', 'Decimal'), ('DATE', 'Date'), ('CURRENCY', 'Currency'), ('DROPDOWN', 'Dropdown List'), ('BOOLEAN', 'Yes / No')], default='TEXT', max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated values for dropdown options', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.TextField(blank=True, null=True)),
                ('field_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='custom_fields.customfielddefinition')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='trips.trip')),
            ],
            options={
                'unique_together': {('trip', 'field_def')},
            },
        ),
    ]
