# Generated by Django 6.1.1 on 2026-09-08 04:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('expenses', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_ref_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ledger_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('bill_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('entry_date', models.DateField(db_index=True)),
                ('period_from', models.DateField(db_index=True)),
                ('period_to', models.DateField(db_index=True)),
                ('from_location', models.CharField(db_index=True, max_length=150)),
                ('to_location', models.CharField(db_index=True, max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('primary_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_trips', to='drivers.driver')),
                ('secondary_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_trips', to='drivers.driver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TripCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Freight')], default='FIXED', max_length=20)),
                ('rate_or_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=150)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('FASTAG', 'FASTag'), ('UPI', 'UPI / GPay / PhonePe'), ('CARD', 'Fuel Card / Debit Card'), ('BANK', 'Bank Transfer')], default='CASH', max_length=30)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_expenses', to='expenses.expensecategory')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripFuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('AdBlue', 'AdBlue / DEF'), ('Engine Oil', 'Engine Oil'), ('Grease', 'Grease / Lubricant')], default='Diesel', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity in liters', max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per liter in ₹', max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('station_name', models.CharField(blank=True, max_length=150, null=True)),
                ('fuel_date', models.DateField()),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripIncomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(default='Freight', max_length=50)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripKMDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_notes', models.TextField(blank=True, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='km_detail', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripLoadingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('weight_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_entries', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripUnloadingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unloading_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('weight_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shortage_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unloading_entries', to='trips.trip')),
            ],
        ),
    ]
