# Generated by Django 5.2.17 on 2026-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripincomeentry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripincomeentry',
            name='custom_income_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
