# Generated by Django 5.2.17 on 2026-09-08 12:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_tripincomeentry_custom_income_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='ledger_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='to_location',
        ),
        migrations.AddField(
            model_name='trip',
            name='header_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
