# Generated by Django 5.2.17 on 2026-09-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_triploadrevenueentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='header_amount',
        ),
    ]
