# Generated by Django 5.2.17 on 2026-09-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_remove_trip_header_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='triploadrevenueentry',
            name='from_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='triploadrevenueentry',
            name='to_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
