# Generated by Django 5.2.17 on 2026-09-09 06:09

from django.db import migrations


def split_from_to(apps, schema_editor):
    TripLoadRevenueEntry = apps.get_model('trips', 'TripLoadRevenueEntry')
    for entry in TripLoadRevenueEntry.objects.all():
        if entry.from_to:
            parts = [p.strip() for p in entry.from_to.replace('->', '→').split('→')]
            entry.from_location = parts[0]
            if len(parts) > 1:
                entry.to_location = parts[1]
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_triploadrevenueentry_from_location_and_more'),
    ]

    operations = [
        migrations.RunPython(split_from_to, reverse_code=migrations.RunPython.noop),
    ]
