# Generated by Django 5.2.17 on 2026-09-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20260909_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triploadrevenueentry',
            name='from_to',
        ),
    ]
