# Generated by Django 5.2.17 on 2026-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_remove_triploadrevenueentry_from_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripfuelentry',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('AdBlue', 'AdBlue')], default='Diesel', max_length=30),
        ),
    ]
