# Generated by Django 5.2.17 on 2026-09-09 07:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('trips', '0010_alter_tripfuelentry_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripexpenseentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='tripexpenseentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_expenses', to='expenses.expensecategory'),
        ),
        migrations.AlterField(
            model_name='tripexpenseentry',
            name='expense_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripexpenseentry',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('FASTAG', 'FASTag'), ('UPI', 'UPI / GPay / PhonePe'), ('CARD', 'Fuel Card / Debit Card'), ('BANK', 'Bank Transfer')], default='CASH', max_length=30, null=True),
        ),
    ]
