# Generated by Django 5.2.17 on 2026-09-10 04:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_tripexpenseentry_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cleaner_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='toll_gate_expense',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='workshop_expense',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
