# Generated by Django 5.2.17 on 2026-09-10 05:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_trip_cleaner_salary_trip_toll_gate_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRtoPcEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150)),
                ('expense_type', models.CharField(choices=[('RTO', 'RTO'), ('PC', 'PC')], default='RTO', max_length=10)),
                ('onward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('return_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rto_pc_entries', to='trips.trip')),
            ],
        ),
    ]
